[formats]
format0 = "%d(%F %T) %us %V %U %L: %m%n"
format1 ="%m%n"

[rules]
flow.!DEBUG >stdout; format0
flow.* "/var/log/semel/flow.log"; format0
ts.!DEBUG >stdout; format1
ts.* "/var/log/semel/ts.log"; format1
metrics.!DEBUG >stdout; format1
metrics.* "/var/log/semel/metrics.log"; format1
data.!DEBUG >stdout; format1
data.* "/var/log/semel/data.log"; format1
